# Generated by Django 2.1 on 2018-09-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0003_auto_20180903_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(upload_to='treasure_images'),
        ),
    ]
