# Generated by Django 2.1 on 2018-09-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0005_auto_20180903_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='default.png', upload_to='treasure_images'),
        ),
    ]
