# Generated by Django 2.1 on 2018-09-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0006_auto_20180904_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
